### PR TITLE
fix(ui): make graph canvas reactive to theme and light/dark mode chan…

### LINKED ISSUE #329: Theme Issues Between Light/Dark
## Summary
When switching between light and dark mode the background of the graph remains dark.

## Description
User experienced a issue when switching between the light and dark mode; graph background remained dark when in light mode.

## Steps to Reproduce
1. Go to [opentrace oss](https://oss.opentrace.ai/)
2. Click on theme button
3. select light theme

## Expected Behavior
User expects light theme to translate into the graph as well as surrounding componantry.

## Actual Behavior
User has dark background for the graph when in light mode.

## Environment
- OS: Linux
- Browser: Google Chrome | Version 146.0.7680.80 (Official Build) (64-bit)

## Screenshots / Logs
N/A 

## Possible Fix
N/A

## Additional Context
N/A

### PR DESCRIPTION
**Pull request by brandontaslater**
## Theme-aware reactivity for Pixi graph canvas
✨ **Improvement** · ♻️ **Refactor**

Replaces hardcoded Pixi.js colors with theme-aware CSS variables. Adds a mutation observer hook to trigger graph background and label updates when the global theme or light/dark mode changes.

### Complexity
🟡 Moderate · `7 files changed, 195 insertions(+), 15 deletions(-)`

The change spans multiple layers: CSS variable definitions, a new MutationObserver hook, and imperative updates to the Pixi.js WebGL renderer. While the logic is clean, it requires synchronizing global DOM state (theme attributes) with an isolated rendering engine, necessitating careful dependency management in React hooks.

### Tests
🧪 Existing tests cover the theme hooks, but no new integration tests were added for the WebGL renderer's reactivity.

### Review focus
Pay particular attention to the following areas:

- **Link color reactivity** — verify if link colors update on theme switch; the renderer currently lacks an explicit `updateLinkColors` method which may leave edges stale until the next data reload.
- **Hex parsing robustness** — check if `parseHexRgb` and `hexToNum` handle 3-digit hex shorthand or invalid strings gracefully.
- **Cache invalidation** — confirm that the `dimColorCache` in `useGraphVisuals` correctly resets to prevent nodes from blending against the previous theme's background.

### CODE REVIEW

File: ui/src/components/graph/useGraphVisuals.ts [hunk 1]
```diff
@@ -27,26 +27,36 @@ import {
...
+  // Invalidate cache when theme changes
+  const root =
+    typeof document !== 'undefined' ? document.documentElement : null;
+  const themeKey = root
+    ? `${root.dataset.theme ?? ''}_${root.dataset.mode ?? ''}`
+    : '';
+  if (themeKey !== dimCacheThemeKey) {
+    dimColorCache = new Map();
+    dimCacheThemeKey = themeKey;
+  }
```
Comment (ghost) [inline ui/src/components/graph/useGraphVisuals.ts:48]: ⚠️ While `dimColor` now correctly invalidates its cache when the theme changes, the `useGraphVisuals` hook's `useEffect` doesn't have `themeKey` in its dependency array. This means the graph colors won't be recomputed and applied when the theme changes, unless some other dependency also changes. You should add `const themeKey = useThemeKey();` inside the hook and add it to the `useEffect` dependencies.

File: ui/src/components/pixi/PixiRenderer.ts [hunk 2]
```diff
@@ -981,6 +982,28 @@ export class PixiRenderer {
...
+      const s = node.label.style;
+      s.fill = themeColors.labelColor;
+      if (s.dropShadow && typeof s.dropShadow === 'object') {
+        s.dropShadow = {
+          ...s.dropShadow,
+          color: themeColors.labelShadow,
+        };
+      }
+    }
+  }
```
Comment (ghost) [inline ui/src/components/pixi/PixiRenderer.ts:1025]: ⚠️ Adding `updateLinkColors` allows changing link colors without calling the expensive `setData()`, enabling fast theme switching for edges as well as nodes.

```suggestion
  /** Re-read graph CSS variables and update canvas background + label styles. */
  setThemeColors(): void {
    if (!this.app) return;
    const themeColors = getGraphThemeColors();

    // Update Pixi canvas background
    this.app.renderer.background.color = hexToNum(themeColors.bg);

    // Update all existing label styles
    for (const node of this.nodes.values()) {
      if (!node.label) continue;
      const s = node.label.style;
      s.fill = themeColors.labelColor;
      if (s.dropShadow && typeof s.dropShadow === 'object') {
        s.dropShadow = {
          ...s.dropShadow,
          color: themeColors.labelShadow,
        };
      }
    }
  }

  /** Update link colors and re-group for batched rendering. */
  updateLinkColors(linkColors: Map<string, string>): void {
    if (!this.app) return;
    for (const edge of this.edges) {
      edge.color = linkColors.get(edge.label) ?? '#3b4048';
    }
    // Pre-group edges by color for batched rendering
    this.edgeColorGroups.clear();
    for (let i = 0; i < this.edges.length; i++) {
      const color = this.edges[i].color;
      let group = this.edgeColorGroups.get(color);
      if (!group) {
        group = [];
        this.edgeColorGroups.set(color, group);
      }
      group.push(i);
    }
    this.redrawAllEdges();
  }
```

File: ui/src/components/PixiGraphCanvas.tsx [hunk 3]
```diff
@@ -314,12 +321,18 @@ const PixiGraphCanvasInner = forwardRef<GraphCanvasHandle, GraphCanvasProps>(
...
     useEffect(() => {
       if (!dataVersion || !rendererRef.current) return;
       rendererRef.current.updateNodeColors(nodeColors);
     }, [dataVersion, nodeColors]);
 
+    // ── Update canvas background + label colors when theme changes ──────
+    useEffect(() => {
+      if (!dataVersion || !rendererRef.current) return;
+      rendererRef.current.setThemeColors();
+    }, [dataVersion, themeKey]);
```
Comment (ghost) [inline ui/src/components/PixiGraphCanvas.tsx:337]: ⚠️ Adding `updateLinkColors` allows changing link colors without calling the expensive `setData()`. Also, consider removing `nodeColors` and `linkColors` from the `setData` effect dependencies to prevent full re-renders on theme switch, as they are now handled by separate effects.

```suggestion
    // ── Update node colors when colorMode or theme changes ────────────
    useEffect(() => {
      if (!dataVersion || !rendererRef.current) return;
      rendererRef.current.updateNodeColors(nodeColors);
    }, [dataVersion, nodeColors]);

    // ── Update link colors when theme changes ─────────────────────────
    useEffect(() => {
      if (!dataVersion || !rendererRef.current) return;
      rendererRef.current.updateLinkColors(linkColors);
    }, [dataVersion, linkColors]);

    // ── Update canvas background + label colors when theme changes ──────
    useEffect(() => {
      if (!dataVersion || !rendererRef.current) return;
      rendererRef.current.setThemeColors();
    }, [dataVersion, themeKey]);
```

File: ui/src/components/graph/useGraphVisuals.ts (hunk 1 above)
Comment (ghost) [reply ui/src/components/graph/useGraphVisuals.ts:48]: Adding `themeKey` to the dependency array in dfdd765 ensures that the graph visuals correctly react to theme changes. Resolving this.

File: ui/src/components/PixiGraphCanvas.tsx (hunk 3 above)
Comment (ghost) [reply ui/src/components/PixiGraphCanvas.tsx:337]: You've added the separate effects for node and link color updates in dfdd765, which is exactly what's needed for fast theme switching. 

However, `nodeColors` and `linkColors` are still in the dependency array for the `setData` effect (around line 319 in `PixiGraphCanvas.tsx`). You should remove them from there; otherwise, a theme change will still trigger the expensive `setData` call, making the new lightweight effects redundant.

File: ui/src/components/pixi/PixiRenderer.ts (hunk 2 above)
Comment (ghost) [reply ui/src/components/pixi/PixiRenderer.ts:1025]: Great addition of `updateLinkColors` and the improved `setThemeColors` in dfdd765. This allows for much smoother theme transitions without full data reloads. I'll mark this as resolved.

File: ui/src/components/PixiGraphCanvas.tsx (hunk 3 above)
Comment (ghost) [reply ui/src/components/PixiGraphCanvas.tsx:337]: You've removed `nodeColors` and `linkColors` from the `setData` effect in e9655f23 and added a clear comment explaining why. This ensures that theme switches only trigger the lightweight color updates instead of a full data reload.

Looks great, I'll mark this as resolved.

**Review by Umaaz — APPROVED** [review]
